version: "3.9" 

services:
  web_api:
    image: ghcr.io/house-stats/web-api:main
    restart: "always"
    environment:
      DBNAME: "house_data"
      PYTHONUNBUFFERED: "1"
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - MONGO_HOST
      - MONGO_USERNAME
      - MONGO_PASSWORD
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
      - SECRET_KEY
    ports:
      - "9800-9810:8000"
    deploy:
      mode: replicated
      replicas: 4
      resources:
        limits:
          cpus: "2"
    networks:
      - net
    depends_on:
      - worker

  worker:
    image: ghcr.io/house-stats/web-api:main
    entrypoint: celery
    command: "--app=app.celery worker --loglevel=info --concurrency=2 
              --without-heartbeat --without-gossip --without-mingle -Ofair"
    restart: "always"
    environment:
      DBNAME: "house_data"
      PYTHONUNBUFFERED: "1"
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - MONGO_HOST
      - MONGO_USERNAME
      - MONGO_PASSWORD
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
      - SECRET_KEY
    deploy:
      mode: replicated
      replicas: 4
      resources:
        limits:
          cpus: "4"
    networks:
      - net
    depends_on:
      - rabbit_mq
      - redis

  update_checker:
    image: ghcr.io/house-stats/update-check:main
    restart: "always"
    environment:
      PYTHONUNBUFFERED: "1"
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - KAFKA
    networks:
      - net

  rabbit_mq:
    image: rabbitmq:3.8-management
    restart: "always"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER_FILE: /run/secrets/RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/RABBITMQ_DEFAULT_PASS
    secrets:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    networks:
      - net

  redis:
    image: redis:latest
    restart: "always"
    ports:
      - '6379:6379'
    networks:
      - net

volumes:
  pgadmin-data:

networks:
  net:

secrets:
  POSTGRES_USER:
    external: true
  POSTGRES_PASSWORD:
    external: true
  POSTGRES_HOST:
    external: true
  MONGO_HOST:
    external: true
  MONGO_USERNAME:
    external: true
  MONGO_PASSWORD:
    external: true
  CELERY_BROKER_URL:
    external: true
  CELERY_RESULT_BACKEND:
    external: true
  SECRET_KEY:
    external: true
  RABBITMQ_DEFAULT_USER:
    external: true
  RABBITMQ_DEFAULT_PASS:
    external: true
  KAFKA:
    external: true