version: "3.9" 

services:
  web_api:
    image: ghcr.io/house-stats/web-api:main
    restart: "always"
    environment:
      DBNAME: "house_data"
      PYTHONUNBUFFERED: "1"
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - MONGO_HOST
      - MONGO_USERNAME
      - MONGO_PASSWORD
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
      - SECRET_KEY
    ports:
      - "9800-9810:8000"
    deploy:
      mode: replicated
      replicas: 4
      resources:
        limits:
          cpus: "2"
    networks:
      - net
    depends_on:
      - worker

  worker:
    image: ghcr.io/house-stats/data-processor:main
    restart: "always"
    environment:
      DBNAME: "house_data"
      PYTHONUNBUFFERED: "1"
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - MONGO_HOST
      - MONGO_USERNAME
      - MONGO_PASSWORD
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
    deploy:
      mode: replicated
      replicas: 4
      resources:
        limits:
          cpus: "4"
    networks:
      - net
    depends_on:
      - rabbit_mq
      - redis

  flower:
    image: ghcr.io/house-stats/data-processor:main
    entrypoint: celery
    command: "--app=worker flower --port=17567"
    restart: "always"
    environment:
      DBNAME: "house_data"
      PYTHONUNBUFFERED: "1"
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - MONGO_HOST
      - MONGO_USERNAME
      - MONGO_PASSWORD
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
    ports:
      - "15445:17567"
    networks:
      - net
    depends_on:
      - rabbit_mq
      - redis

  update_checker:
    image: ghcr.io/house-stats/update-check:main
    restart: "always"
    environment:
      PYTHONUNBUFFERED: "1"
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
    networks:
      - net

  rabbit_mq:
    image: rabbitmq:3.8-management
    restart: "always"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER_FILE: /run/secrets/RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/RABBITMQ_DEFAULT_PASS
    secrets:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    networks:
      - net

  redis:
    image: redis:latest
    restart: "always"
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - '6379:6379'
    networks:
      - net
    volumes:
      - redis-data:/data

volumes:
  redis-data:

networks:
  net:

secrets:
  POSTGRES_USER:
    external: true
  POSTGRES_PASSWORD:
    external: true
  POSTGRES_HOST:
    external: true
  MONGO_HOST:
    external: true
  MONGO_USERNAME:
    external: true
  MONGO_PASSWORD:
    external: true
  CELERY_BROKER_URL:
    external: true
  CELERY_RESULT_BACKEND:
    external: true
  SECRET_KEY:
    external: true
  RABBITMQ_DEFAULT_USER:
    external: true
  RABBITMQ_DEFAULT_PASS:
    external: true
  KAFKA:
    external: true